################################################################
## Packages / Ladestasjoner
##
## Lagt inn to klokkeslett for å starte ladestasjonene og
## to klokkeslett for å stoppe de om dagen / natta
##
## Enjoy and share - Tor Gaute Lien 2020
##
################################################################

################################################################
## WHAT YOU NEED TO MAKE IT WORK (PACKAGES):
## 
## You need to use the package feature in Home Assistant
## https://www.home-assistant.io/docs/configuration/packages/
##
## Add a folder in your config-folder named "packages"
## 
## Add following line in configuration.yaml:
## packages: !include_dir_named packages
## 
## Next step is to store the package in the folder "packages"
## When it is stored or changed, you need to then reboot HA
##
################################################################

################################################################
## VERSIONLOG
##
## VERSJON 1.0 - NEW
## 13/4-20
## 
################################################################

################################################################
## CHANGES YOU NEED TO DO
## 
## Mange, bruk denne til inspirasjon eventuelt!
## 
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'pakker-ladestasjoner'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

################################################
## INPUTS
################################################

input_boolean:

  # LADESTASJON STUE
  ladestasjon_stue_enable:
    name: "Ladestasjon: Aktiver ladestasjon Stue"
    icon: mdi:bell

  # LADESTASJON TG
  ladestasjon_tg_enable:
    name: "Ladestasjon: Aktiver ladestasjon TG"
    icon: mdi:bell

  # LADESTASJON SILJE
  ladestasjon_silje_enable:
    name: "Ladestasjon: Aktiver ladestasjon Silje"
    icon: mdi:bell


input_datetime:

  # LADESTASJON STUE
  ladestasjon_stue_on_1:
    name: "Skru på"
    has_date: false
    has_time: true
  ladestasjon_stue_on_2:
    name: "Skru på"
    has_date: false
    has_time: true
  ladestasjon_stue_off_1:
    name: "Skru av"
    has_date: false
    has_time: true
  ladestasjon_stue_off_2:
    name: "Skru av"
    has_date: false
    has_time: true
    
  # LADESTASJON TG
  ladestasjon_tg_on_1:
    name: "Skru på"
    has_date: false
    has_time: true
  ladestasjon_tg_on_2:
    name: "Skru på"
    has_date: false
    has_time: true
  ladestasjon_tg_off_1:
    name: "Skru av"
    has_date: false
    has_time: true
  ladestasjon_tg_off_2:
    name: "Skru av"
    has_date: false
    has_time: true
    
  # LADESTASJON SILJE
  ladestasjon_silje_on_1:
    name: "Skru på"
    has_date: false
    has_time: true
  ladestasjon_silje_on_2:
    name: "Skru på"
    has_date: false
    has_time: true
  ladestasjon_silje_off_1:
    name: "Skru av"
    has_date: false
    has_time: true
  ladestasjon_silje_off_2:
    name: "Skru av"
    has_date: false
    has_time: true


################################################
## SCRIPT
################################################

script:
            
  ################################################################
  ## LADESTASJON STUE
  ################################################################
  
  ladestasjon_stue_on_script:
    alias: "Ladestasjon Stue: På"
    sequence:
      - service: homeassistant.turn_on
        data: 
          entity_id: switch.stue_ladestasjon_switch
          
  ladestasjon_stue_off_script:
    alias: "Ladestasjon Stue: Av"
    sequence:
      - service: homeassistant.turn_off
        data: 
          entity_id: switch.stue_ladestasjon_switch
          
  ################################################################
  ## LADESTASJON TG
  ################################################################
  
  ladestasjon_tg_on_script:
    alias: "Ladestasjon TG: På"
    sequence:
      - service: homeassistant.turn_on
        data: 
          entity_id: switch.soverom_lading_tg_switch
          
  ladestasjon_tg_off_script:
    alias: "Ladestasjon TG: Av"
    sequence:
      - service: homeassistant.turn_off
        data: 
          entity_id: switch.soverom_lading_tg_switch

  ################################################################
  ## LADESTASJON SILJE
  ################################################################
  
  ladestasjon_silje_on_script:
    alias: "Ladestasjon Silje: På"
    sequence:
      - service: homeassistant.turn_on
        data: 
          entity_id: switch.soverom_lading_silje_switch
          
  ladestasjon_silje_off_script:
    alias: "Ladestasjon Silje: Av"
    sequence:
      - service: homeassistant.turn_off
        data: 
          entity_id: switch.soverom_lading_silje_switch


################################################
## AUTOMATION
################################################

automation:

  ################################################################
  ## LADESTASJON STUE
  ################################################################

  # PÅ
  - id: ladestasjon_stue_on
    alias: "Ladestasjon Stue: På"
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.ladestasjon_stue_on_1.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.ladestasjon_stue_on_2.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    condition:
      - condition: state
        entity_id: input_boolean.ladestasjon_stue_enable
        state: 'on'
    action:
      service: script.ladestasjon_stue_on_script

  # AV
  - id: ladestasjon_stue_off
    alias: "Ladestasjon Stue: Av"
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.ladestasjon_stue_off_1.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.ladestasjon_stue_off_2.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    condition:
      - condition: state
        entity_id: input_boolean.ladestasjon_stue_enable
        state: 'on'
    action:
      service: script.ladestasjon_stue_off_script
      
  ################################################################
  ## LADESTASJON TG
  ################################################################

  # PÅ
  - id: ladestasjon_tg_on
    alias: "Ladestasjon TG: På"
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.ladestasjon_tg_on_1.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.ladestasjon_tg_on_2.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    condition:
      - condition: state
        entity_id: input_boolean.ladestasjon_tg_enable
        state: 'on'
    action:
      service: script.ladestasjon_tg_on_script

  # AV
  - id: ladestasjon_tg_off
    alias: "Ladestasjon TG: Av"
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.ladestasjon_tg_off_1.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.ladestasjon_tg_off_2.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    condition:
      - condition: state
        entity_id: input_boolean.ladestasjon_tg_enable
        state: 'on'
    action:
      service: script.ladestasjon_tg_off_script

  ################################################################
  ## LADESTASJON SILJE
  ################################################################

  # PÅ
  - id: ladestasjon_silje_on
    alias: "Ladestasjon Silje: På"
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.ladestasjon_silje_on_1.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.ladestasjon_silje_on_2.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    condition:
      - condition: state
        entity_id: input_boolean.ladestasjon_silje_enable
        state: 'on'
    action:
      service: script.ladestasjon_silje_on_script

  # AV
  - id: ladestasjon_silje_off
    alias: "Ladestasjon Silje: Av"
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.ladestasjon_silje_off_1.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
      - platform: template
        value_template: "{{ states('sensor.time') == (states.input_datetime.ladestasjon_silje_off_2.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    condition:
      - condition: state
        entity_id: input_boolean.ladestasjon_silje_enable
        state: 'on'
    action:
      service: script.ladestasjon_silje_off_script
