################################################################
## packages-posten --> Versjon 1.2 --> 25/01-22
##
## BESKRIVELSE
##
## Her får du to sensorer som henter informasjon fra Posten over
## når posten blir levert til din postadresse
##
## sensor.posten vil være True om posten blir hentet i dag, og ha
## attributes som forteller de neste dagene Posten blir levert
##
## sensor.postendeliverydays vil vise de neste dagene
## Posten blir levert
##
## sensor.postlevering vil vise i dag, i morgen eller neste dato
## Posten blir levert. Ikonet blir åpent om det er i dag.
##
## binary_sensor.posten vil endre farge (aktiveres) om
## posten blir levert i dag
##
## Under automation vil den klokken 12:13:14 de dagene det er post
## sende notifikasjon til alle under notify
##
## Du må endre 2847 til ditt postnummer så er du i gang!
##
## scan_interval er hvor ofte den sjekker i sekunder (16 timer)
##
################################################################

################################################################
## VERSJONLOG
##
## VERSJON  1.2 - Nye sensorer
## 25/01-22
## Lagt inn PostenDeliveryDays (som kan brukes på Posten-kortet)
## Lagt inn Postlevering (etter kode fra Simen Randen, HA Norge)
##
## VERSJON  1.1 - Posten
## 29/12-21
## Endret adressen da Posten endret adresse...
##
## VERSJON  1.0 - Posten
## 7/8-20
## Kopiert fra sensor laget av Erlend Sellie fra forumet
## "Home Asssitant Norge" på Facebook
##
## Lagt inn som pakke og skrevet hjelpetekster
##
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "packages-posten"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    sensor.posten:
      icon: mdi:bugle

    binary_sensor.posten:
      icon: mdi:bugle

################################################
## SENSOR
################################################

sensor:
  # Sensor som er True når dagen er i dag
  # HER MÅ DU ENDRE TIL DITT POSTNUMMER FRA 2847
  - platform: command_line
    command: >-
      curl 'https://www.posten.no/levering-av-post/_/component/main/1/leftRegion/1?postCode=2847' \
        -H 'x-requested-with: XMLHttpRequest' \
        --compressed
    name: Posten
    json_attributes:
      - nextDeliveryDays
    value_template: "{{'i dag' in (value_json.nextDeliveryDays | string) }}"
    scan_interval: 28800
    command_timeout: 30

  # Sensor som brukes av blant annet Posten-Card og viser datoene
  # HER MÅ DU ENDRE TIL DITT POSTNUMMER FRA 2847
  - platform: rest
    name: PostenDeliveryDays
    resource: https://www.posten.no/levering-av-post/_/component/main/1/leftRegion/1?postCode=2847
    headers:
      x-requested-with: XMLHttpRequest
    scan_interval: 28800
    value_template: "{{ value_json.nextDeliveryDays }}"

  # Sensor som gir forskjellig ikon og sier i dag, i morgen eller neste dag (bruker PostenDeliveryDays sensoren)
  - platform: template
    sensors:
      post_levering:
        friendly_name: Postlevering
        value_template: >-
          {% set neste = states('sensor.postendeliverydays').split("'")[1] %}
          {% set post = neste.split()[0] %}
          {% if post == 'i' %}
          {% set post = neste.split()[0]+' '+neste.split()[1] %}
          {% endif %}
          {{(post)|capitalize}}
        icon_template: >-
          {% set neste = states('sensor.postendeliverydays').split("'")[1] %}
          {% set post = neste.split()[0] %}
          {% if post == 'i' %}
          {% set post = neste.split()[0]+' '+neste.split()[1] %}
          {% endif %}
          {% if post == 'i dag' %}
            mdi:mailbox-open
          {% else %}
            mdi:mailbox
          {% endif %}

binary_sensor:
  # Binary sensor som er aktiv når det er levering
  - platform: template
    sensors:
      posten:
        friendly_name: "Posten"
        value_template: "{{ is_state('sensor.posten', 'True') }}"

################################################
## AUTOMATION
################################################

automation:
  - alias: "Posten: Posten kommer i dag"
    trigger:
      - at: "12:13:14"
        platform: time
    condition:
      - condition: state
        entity_id: binary_sensor.posten
        state: "on"
    action:
      - service: notify.notify
        data_template:
          message: "Husk å hente posten!"
          title: "Posten kommer i dag!"
