################################################################
## packages-alarm --> Versjon 2.0 --> 19/1-22
##
## BESKRIVELSE
##
## Pakke som gir følgende devices per alarm:
## Input Datetime som gir klokkeslett alarm
## Input Boolean som kan aktivere / deaktivere alarmene totalt
## Input Boolean som kan aktivere / deaktivere enkelt alarmen
## Binary Sensor (workday) som sier ifra om det er skoledag
##
################################################################

################################################################
## VERSJONLOG
##
## VERSJON  2.0 - Node-RED
## 19/1-22
## Fjernet automasjoner (til NR) og gjort pakken til ren enhetspakke
## Enhetene har like navn, det eneste som endres på slutten er navnet
## Delt opp i tre pakker: alarm, alarm_busstid og alarm_leggetid
##
## VERSJON  1.1 - VACATION-MODE
## 15/4-20
## Lagt inn Vacation-mode slik at når den er aktivert er
## skole og bussalarmene på pause
##
## Vacation-mode er en input_boolean som jeg har i egen pakke
## da jeg bruker den samme på mange forskjellige pakker
## Husk å legge inn denne pakken også eller fjern featuren
##
## VERSJON 1.0 - NEW
## 13/4-20
##
## Alarm skole og buss for Matthias og Sofie
## Alarmene har egne klokkeslett og brytere
## De har hver sin hovedbryter og det er en felles hovedbryter
## Alarmene bruker en sensor (Skoledag) for å skille skoledag og fri
##
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "packages-alarm"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

################################################
## INPUTS
################################################

input_boolean:
  # ALARM
  alarm_enable:
    name: "Alarm: Aktiver alarmer"
    icon: mdi:bell
  # ALARM MATHIAS
  alarm_mathias:
    name: "Alarm Mathias"
    icon: mdi:bell
  # ALARM SOFIE
  alarm_sofie:
    name: "Alarm Sofie"
    icon: mdi:bell

input_datetime:
  # ALARM MATHIAS
  alarm_mathias:
    name: "Alarm"
    has_date: false
    has_time: true

  # ALARM SOFIE
  alarm_sofie:
    name: "Alarm"
    has_date: false
    has_time: true

################################################
## BINARY SENSOR
################################################

binary_sensor:
  # SKOLEDAG
  - platform: workday
    country: "NO"
    name: "Skoledag"
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]
    add_holidays:
      - "2020-05-02"
      - "2020-05-22"
      - "2020-06-01"
    # Her kan man legge inn planleggingsdatoer etc som man vet skolen er stengt
################################################
## SCRIPT
################################################
#script:
#  ################################################################
#  ## SKOLETID VEKKING MATHIAS
#  ################################################################
#
#  alarm_busstid_mathias:
#    sequence:
#      - service: media_player.volume_set
#        data_template:
#          entity_id: media_player.mathias
#          volume_level: 0.6
#      - service: media_player.play_media
#        entity_id: media_player.mathias
#        data:
#          media_content_id: !secret vekking
#          media_content_type: music
#      - delay: 00:00:09
#      - service: tts.google_translate_say
#        entity_id: media_player.mathias
#        data_template:
#          message: "God morgen Mathias! Klokken er {{  states.sensor.time.state }} og det er på tide å stå opp!"
#      - delay: 00:00:09
#      - service: media_player.play_media
#        entity_id: media_player.mathias
#        data:
#          media_content_id: !secret vekking
#          media_content_type: music
#      - delay: 00:00:09
#      - service: media_player.volume_set
#        data_template:
#          entity_id: media_player.mathias
#          volume_level: 0.4
#
#  ################################################################
#  ## SKOLETID BUSSVARSEL MATHIAS
#  ################################################################
#
#  alarm_busstid_buss_mathias:
#    sequence:
#      - service: media_player.volume_set
#        data_template:
#          entity_id: media_player.sonos
#          volume_level: 0.6
#      - data_template:
#          message: "Mathias og Sofie, nå må dere gjøre dere klare til bussen! Klokken er {{  states.sensor.time.state }}!"
#        entity_id: media_player.sonos
#        service: tts.google_translate_say
#      - delay: 00:00:03
#
#
################################################
## AUTOMATION
################################################
#automation:
#  ################################################################
#  ## SKOLETID
#  ################################################################
#
#  # MATHIAS VEKKING
#  - id: alarm_busstid_mathias
#    alias: "Skoletid: Vekking Mathias"
#    trigger:
#      platform: template
#      value_template: "{{ states('sensor.time') == (states.input_datetime.alarm_busstid_mathias.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
#    condition:
#      - condition: state
#        entity_id: input_boolean.alarm_busstid_enable
#        state: "on"
#      - condition: state
#        entity_id: input_boolean.alarm_busstid_mathias
#        state: "on"
#      - condition: state
#        entity_id: input_boolean.vacation_mode
#        state: "off"
#      - condition: state
#        entity_id: input_boolean.vacation_mode
#        state: "off"
#    action:
#      service: script.alarm_busstid_mathias
#
#  # MATHIAS BUSS
#  - id: alarm_busstid_buss_mathias
#    alias: "Skoletid: Buss Mathias"
#    trigger:
#      platform: template
#      value_template: "{{ states('sensor.time') == (states.input_datetime.alarm_busstid_buss_mathias.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
#    condition:
#      - condition: state
#        entity_id: input_boolean.alarm_busstid_enable
#        state: "on"
#      - condition: state
#        entity_id: input_boolean.alarm_busstid_buss_mathias
#        state: "on"
#      - condition: state
#        entity_id: input_boolean.vacation_mode
#        state: "off"
#      - condition: state
#        entity_id: input_boolean.vacation_mode
#        state: "off"
#    action:
#      service: script.alarm_busstid_buss_mathias
