################################################################
## packages-arbeidsdag --> Versjon 1.1 --> 19/1-22
##
## BESKRIVELSE
##
## Lager en binary sensor som heter Arbeidsdag som forteller
## hvilke dager som er arbeidsdager og hvilke som er helg / hellig.
##
## Denne brukes til å styre ladestasjonene min (slå de av til tider)
##
## PS: Onsdag har fruen fri, så det er helgedag...
##
## Laget en sensor arbeidsdag_tg som er mandag til fredag
##
################################################################

################################################################
## VERSJONSLOGG
##
## VERSJON 1.1 - Arbeidsdag_TG
## 19/1-22
## Laget arbeidsdag_tg som er vanlig arbeidsuke for meg
##
## VERSJON 1.0 - Ny
## 31/12-21
## Laget denne
##
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "packages-arbeidsdag"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

################################################
## BINARY SENSOR
################################################

binary_sensor:
  - platform: workday
    country: "NO"
    name: "Arbeidsdag"
    workdays: [mon, tue, thu, fri]
    excludes: [wed, sat, sun, holiday]

  - platform: workday
    country: "NO"
    name: "Arbeidsdag_TG"
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]
