### AUTOMASJONER BØR ENDRES TIL NODE RED -> TING Å GJØRE

################################################################
## packages-alarmer --> Versjon 1.1 --> 15/4-20
##
## BESKRIVELSE
##
## Alarm leggetid Marthias, Sofie og voksne.
## Alarmene har egne klokkeslett og brytere for hverdager og helg
## De har hver sin hovedbryter
## Alarmene bruker en sensor (Leggetid) for å skille hverdag og helg
##
## Alarm skole og buss for Matthias og Sofie
## Alarmene har egne klokkeslett og brytere
## De har hver sin hovedbryter og det er en felles hovedbryter
## Alarmene bruker en sensor (Skoledag) for å skille skoledag og fri
##
## Lagt inn Vacation-mode slik at når den er aktivert er
## skole og bussalarmene på pause
##
################################################################

################################################################
## VERSJONLOG
##
## VERSJON  1.1 - VACATION-MODE
## 15/4-20
## Lagt inn Vacation-mode slik at når den er aktivert er
## skole og bussalarmene på pause
##
## Vacation-mode er en input_boolean som jeg har i egen pakke
## da jeg bruker den samme på mange forskjellige pakker
## Husk å legge inn denne pakken også eller fjern featuren
##
## VERSJON 1.0 - NEW
## 13/4-20
##
## Alarm leggetid Marthias, Sofie og voksne.
## Alarmene har egne klokkeslett og brytere for hverdager og helg
## De har hver sin hovedbryter
## Alarmene bruker en sensor (Leggetid) for å skille hverdag og helg
##
## Alarm skole og buss for Matthias og Sofie
## Alarmene har egne klokkeslett og brytere
## De har hver sin hovedbryter og det er en felles hovedbryter
## Alarmene bruker en sensor (Skoledag) for å skille skoledag og fri
##
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "packages-alarmer"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

################################################
## INPUTS
################################################

input_boolean:
  # LEGGETID MATHIAS
  leggetid_mathias_enable:
    name: "Leggetid: Aktiver leggetid Mathias"
    icon: mdi:bell
  leggetid_ukedager_mathias:
    name: Ukedager
    icon: mdi:calendar
  leggetid_helg_mathias:
    name: Helg
    icon: mdi:calendar

  # LEGGETID SOFIE
  leggetid_sofie_enable:
    name: "Leggetid: Aktiver leggetid Sofie"
    icon: mdi:bell
  leggetid_ukedager_sofie:
    name: Ukedager
    icon: mdi:calendar
  leggetid_helg_sofie:
    name: Helg
    icon: mdi:calendar

  # LEGGETID VOKSNE
  leggetid_voksne_enable:
    name: "Leggetid: Aktiver leggetid voksne"
    icon: mdi:bell
  leggetid_ukedager_voksne:
    name: Ukedager
    icon: mdi:calendar
  leggetid_helg_voksne:
    name: Helg
    icon: mdi:calendar

  # SKOLETID
  skoletid_enable:
    name: "Skoletid: Aktiver alarmer og bussvarsel"
    icon: mdi:bell
  skoletid_mathias:
    name: "Alarm Mathias"
    icon: mdi:bell
  skoletid_buss_mathias:
    name: "Buss Mathias"
    icon: mdi:bell
  skoletid_sofie:
    name: "Alarm Sofie"
    icon: mdi:bell
  skoletid_buss_sofie:
    name: "Buss Sofie"
    icon: mdi:bell

input_datetime:
  # LEGGETID MATHIAS
  leggetid_ukedager_mathias:
    name: "Leggetid ukedager"
    has_date: false
    has_time: true
  leggetid_helg_mathias:
    name: "Leggetid helg"
    has_date: false
    has_time: true

  # LEGGETID SOFIE
  leggetid_ukedager_sofie:
    name: "Leggetid ukedager"
    has_date: false
    has_time: true
  leggetid_helg_sofie:
    name: "Leggetid helg"
    has_date: false
    has_time: true

  # LEGGETID VOKSNE
  leggetid_ukedager_voksne:
    name: "Leggetid ukedager"
    has_date: false
    has_time: true
  leggetid_helg_voksne:
    name: "Leggetid helg"
    has_date: false
    has_time: true

  # SKOLETID MATHIAS
  skoletid_mathias:
    name: "Alarm"
    has_date: false
    has_time: true
  skoletid_buss_mathias:
    name: "Bussvarsel"
    has_date: false
    has_time: true

  # SKOLETID SOFIE
  skoletid_sofie:
    name: "Alarm"
    has_date: false
    has_time: true
  skoletid_buss_sofie:
    name: "Bussvarsel"
    has_date: false
    has_time: true

################################################
## BINARY SENSOR
################################################

binary_sensor:
  # LEGGETID
  - platform: workday
    country: "NO"
    name: "Leggetid"
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]
    days_offset: 1

  # SKOLEDAG
  - platform: workday
    country: "NO"
    name: "Skoledag"
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]
    add_holidays:
      - "2020-05-02"
      - "2020-05-22"
      - "2020-06-01"
    # Her kan man legge inn planleggingsdatoer etc som man vet skolen er stengt

################################################
## SCRIPT
################################################

script:
  ################################################################
  ## LEGGETID MATHIAS
  ################################################################

  leggetid_mathias_script:
    alias: "Leggetid: Mathias"
    sequence:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.sonos
          volume_level: 0.6
      - data_template:
          message: "Mathias! Klokken er {{  states.sensor.time.state }}, på tide å legge seg! God natt!"
        entity_id: media_player.sonos
        service: tts.google_translate_say

  ################################################################
  ## LEGGETID SOFIE
  ################################################################

  leggetid_sofie_script:
    alias: "Leggetid: Sofie"
    sequence:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.sonos
          volume_level: 0.6
      - data_template:
          message: "Sofie! Klokken er {{  states.sensor.time.state }}, på tide å legge seg! God natt!"
        entity_id: media_player.sonos
        service: tts.google_translate_say

  ################################################################
  ## LEGGETID VOKSNE
  ################################################################

  leggetid_voksne_script:
    alias: "Leggetid: Voksne"
    sequence:
      - service: notify.mobile_app_toakens_iphone
        data:
          title: "Nå er det leggetid!"
          message: "God natt!"
      - service: notify.mobile_app_siljes_iphone
        data:
          title: "Nå er det leggetid!"
          message: "God natt!"
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.sonos
          volume_level: 0.6
      - data_template:
          message: "Klokken er {{  states.sensor.time.state }}, på tide å legge seg! God natt!"
        entity_id: media_player.sonos
        service: tts.google_translate_say
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.smiubakken
          volume_level: 0.6
      - data_template:
          message: "Klokken er {{  states.sensor.time.state }}, på tide å legge seg! God natt!"
        entity_id: media_player.smiubakken
        service: tts.google_translate_say

  ################################################################
  ## SKOLETID VEKKING MATHIAS
  ################################################################

  skoletid_mathias:
    sequence:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.mathias
          volume_level: 0.6
      - service: media_player.play_media
        entity_id: media_player.mathias
        data:
          media_content_id: !secret vekking
          media_content_type: music
      - delay: 00:00:09
      - service: tts.google_translate_say
        entity_id: media_player.mathias
        data_template:
          message: "God morgen Mathias! Klokken er {{  states.sensor.time.state }} og det er på tide å stå opp!"
      - delay: 00:00:09
      - service: media_player.play_media
        entity_id: media_player.mathias
        data:
          media_content_id: !secret vekking
          media_content_type: music
      - delay: 00:00:09
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.mathias
          volume_level: 0.4

  ################################################################
  ## SKOLETID VEKKING SOFIE
  ################################################################

  skoletid_sofie:
    sequence:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.sofie
          volume_level: 0.6
      - service: media_player.play_media
        entity_id: media_player.sofie
        data:
          media_content_id: !secret vekking2
          media_content_type: music
      - delay: 00:00:08
      - service: tts.google_translate_say
        entity_id: media_player.sofie
        data_template:
          message: "God morgen Sofie! Klokken er {{  states.sensor.time.state }} og det er på tide å stå opp!"
      - delay: 00:00:08
      - service: media_player.play_media
        entity_id: media_player.sofie
        data:
          media_content_id: !secret vekking2
          media_content_type: music
      - delay: 00:00:08
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.sofie
          volume_level: 0.2

  ################################################################
  ## SKOLETID BUSSVARSEL MATHIAS
  ################################################################

  skoletid_buss_mathias:
    sequence:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.sonos
          volume_level: 0.6
      - data_template:
          message: "Mathias og Sofie, nå må dere gjøre dere klare til bussen! Klokken er {{  states.sensor.time.state }}!"
        entity_id: media_player.sonos
        service: tts.google_translate_say
      - delay: 00:00:03

  ################################################################
  ## SKOLETID BUSSVARSEL SOFIE
  ################################################################

  skoletid_buss_sofie:
    sequence:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.sonos
          volume_level: 0.6
      - data_template:
          message: "Mathias og Sofie, nå må dere gå ut til bussen! Klokken er {{  states.sensor.time.state }}!"
        entity_id: media_player.sonos
        service: tts.google_translate_say
      - delay: 00:00:03

  leggetid_test_script:
    alias: "Leggetid: Test"
    sequence:
      - data_template:
          message: "Det funker! Klokken er {{  states.sensor.time.state }} !"
        entity_id: media_player.sonos
        service: tts.google_translate_say

################################################
## AUTOMATION
################################################
automation:
  ################################################################
  ## LEGGETID MATHIAS
  ################################################################

  # UKEDAGER
  - id: leggetid_ukedager_mathias

    alias: "Leggetid: Mathias leggetid ukedager"

    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.leggetid_ukedager_mathias.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"

    condition:
      - condition: state
        entity_id: input_boolean.leggetid_mathias_enable
        state: "on"
      - condition: state
        entity_id: input_boolean.leggetid_ukedager_mathias
        state: "on"
      - condition: state
        entity_id: binary_sensor.leggetid
        state: "on"

    action:
      service: script.leggetid_mathias_script

  # HELG
  - id: leggetid_helg_mathias

    alias: "Leggetid: Mathias leggetid helg"

    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.leggetid_helg_mathias.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"

    condition:
      - condition: state
        entity_id: input_boolean.leggetid_mathias_enable
        state: "on"
      - condition: state
        entity_id: input_boolean.leggetid_helg_mathias
        state: "on"
      - condition: state
        entity_id: binary_sensor.leggetid
        state: "off"

    action:
      service: script.leggetid_mathias_script

  ################################################################
  ## LEGGETID SOFIE
  ################################################################

  # UKEDAGER
  - id: leggetid_ukedager_sofie

    alias: "Leggetid: Sofie leggetid ukedager"

    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.leggetid_ukedager_sofie.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"

    condition:
      - condition: state
        entity_id: input_boolean.leggetid_sofie_enable
        state: "on"
      - condition: state
        entity_id: input_boolean.leggetid_ukedager_sofie
        state: "on"
      - condition: state
        entity_id: binary_sensor.leggetid
        state: "on"

    action:
      service: script.leggetid_sofie_script

  # HELG
  - id: leggetid_helg_sofie

    alias: "Leggetid: Sofie leggetid helg"

    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.leggetid_helg_sofie.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"

    condition:
      - condition: state
        entity_id: input_boolean.leggetid_sofie_enable
        state: "on"
      - condition: state
        entity_id: input_boolean.leggetid_helg_sofie
        state: "on"
      - condition: state
        entity_id: binary_sensor.leggetid
        state: "off"

    action:
      service: script.leggetid_sofie_script

  ################################################################
  ## LEGGETID VOKSNE
  ################################################################

  # UKEDAGER
  - id: leggetid_ukedager_voksne

    alias: "Leggetid: Voksne leggetid ukedager"

    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.leggetid_ukedager_voksne.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"

    condition:
      - condition: state
        entity_id: input_boolean.leggetid_voksne_enable
        state: "on"
      - condition: state
        entity_id: input_boolean.leggetid_ukedager_voksne
        state: "on"
      - condition: state
        entity_id: binary_sensor.leggetid
        state: "on"

    action:
      service: script.leggetid_voksne_script

  # HELG
  - id: leggetid_helg_voksne

    alias: "Leggetid: Voksne leggetid helg"

    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.leggetid_helg_voksne.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"

    condition:
      - condition: state
        entity_id: input_boolean.leggetid_voksne_enable
        state: "on"
      - condition: state
        entity_id: input_boolean.leggetid_helg_voksne
        state: "on"
      - condition: state
        entity_id: binary_sensor.leggetid
        state: "off"

    action:
      service: script.leggetid_voksne_script

  ################################################################
  ## SKOLETID
  ################################################################

  # MATHIAS VEKKING
  - id: skoletid_mathias

    alias: "Skoletid: Vekking Mathias"

    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.skoletid_mathias.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"

    condition:
      - condition: state
        entity_id: input_boolean.skoletid_enable
        state: "on"
      - condition: state
        entity_id: input_boolean.skoletid_mathias
        state: "on"
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"

    action:
      service: script.skoletid_mathias

  # MATHIAS BUSS
  - id: skoletid_buss_mathias

    alias: "Skoletid: Buss Mathias"

    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.skoletid_buss_mathias.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"

    condition:
      - condition: state
        entity_id: input_boolean.skoletid_enable
        state: "on"
      - condition: state
        entity_id: input_boolean.skoletid_buss_mathias
        state: "on"
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"

    action:
      service: script.skoletid_buss_mathias

  # SOFIE
  - id: skoletid_sofie

    alias: "Skoletid: Vekking Sofie"

    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.skoletid_sofie.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"

    condition:
      - condition: state
        entity_id: input_boolean.skoletid_enable
        state: "on"
      - condition: state
        entity_id: input_boolean.skoletid_sofie
        state: "on"
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"

    action:
      service: script.skoletid_sofie

  # MATHIAS BUSS
  - id: skoletid_buss_sofie

    alias: "Skoletid: Buss Sofie"

    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.skoletid_buss_sofie.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"

    condition:
      - condition: state
        entity_id: input_boolean.skoletid_enable
        state: "on"
      - condition: state
        entity_id: input_boolean.skoletid_buss_sofie
        state: "on"
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"

    action:
      service: script.skoletid_buss_sofie
