################################################################
## packages-energi_energy --> Versjon 1.2 --> 24/01-22
##
## BESKRIVELSE
##
## Her legger jeg på energy (kWh) på enheter som ikke
## har måler i seg. Det regnes ut fra strømforbruk (power).
##
## Jeg lager også egen energy (kWh) på enhet der jeg bruker filter.
##
################################################################

################################################################
## VERSJONLOG
##
## VERSJON 1.2 - Lagt inn filter
## 24/01-22
## Lagt inn filter på to enheter som rapporterte spikes
##
## VERSJON 1.1 - Endret navn
## 11/01-22
## Endret navn på pakken fra energy til energi_energy
##
## VERSJON 1.0 - Ny
## 08/02-22
## Laget infotekst
##
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "packages-energi_energy"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## SENSOR
    ################################################

    sensor.tibber_spent:
      icon: mdi:gauge
    sensor.600w_spent:
      icon: mdi:gauge
    sensor.varme_spent:
      icon: mdi:gauge
    sensor.smiubakken_termostat_energy_filter:
      icon: mdi:gauge
    sensor.gang_termostat_energy_filter:
      icon: mdi:gauge

################################################
## SENSOR
################################################

sensor:
  #OMREGNER: Regne om power til effekt - Tibber
  - platform: integration
    source: sensor.power_dystlinna_249
    name: tibber_spent
    unit_prefix: k
    round: 2

  #OMREGNER: Regne om power til effekt - 600w Barneloft
  - platform: integration
    source: sensor.600w_power
    name: 600w_spent
    unit_prefix: k
    round: 2

  #OMREGNER: Regne om power til effekt - Lekerom Varmeovn
  - platform: integration
    source: sensor.lekerom_varmeovn_power
    name: lekerom_varmeovn_energy
    unit_prefix: k
    round: 2

  #OMREGNER: Regne om power til effekt - Kontor Varmeovn
  - platform: integration
    source: sensor.kontor_varmeovn_power
    name: kontor_varmeovn_energy
    unit_prefix: k
    round: 2

  #OMREGNER: Regne om power til effekt - Stuelys
  - platform: integration
    source: sensor.stue_lys_power
    name: stue_lys_energy
    unit_prefix: k
    round: 2

  #OMREGNER: Regne om power til effekt - Varme
  - platform: integration
    source: sensor.varme_power
    name: varme_spent
    unit_prefix: k
    round: 2

  #OMREGNER: Regne om power til effekt - Smiubakken Termostat FILTER
  - platform: integration
    source: sensor.smiubakken_termostat_power_filter
    name: smiubakken_termostat_energy_filter
    unit_prefix: k
    round: 2

  #OMREGNER: Regne om power til effekt - Gang Termostat FILTER
  - platform: integration
    source: sensor.gang_termostat_power_filter
    name: gang_termostat_energy_filter
    unit_prefix: k
    round: 2
