################################################################
## Packages / Vacation
##
## Creates an input boolean called vacation_mode and home_mode 
## 
## These may be used in automations to override features as needed
##
## Enjoy and share - Tor Gaute Lien 2020
##
################################################################

################################################################
## WHAT YOU NEED TO MAKE IT WORK (PACKAGES):
## 
## You need to use the package feature in Home Assistant
## https://www.home-assistant.io/docs/configuration/packages/
##
## Add a folder in your config-folder named "packages"
## 
## Add following line in configuration.yaml:
## packages: !include_dir_named packages
## 
## Next step is to store the package in the folder "packages"
## When it is stored or changed, you need to then reboot HA
##
################################################################

################################################################
## VERSIONLOG
##
## VERSJON 1.1 - HOME FUNCTION
## 9/8-20
##
## Added home function to override features when you are home
## sick or home in vacation / holidays
## 
## VERSJON 1.0 - NEW
## 17/4-20
##
## Created infotext and instructions
## 
################################################################

################################################################
## CHANGES YOU NEED TO DO
## 
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Vacation'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

################################################
## INPUT BOOLEAN
################################################

input_boolean:

  #Feriemodus
  vacation_mode:
    name: Feriemodus
    icon: mdi:airplane

  #Hjemmemodus
  home_mode:
    name: Hjemmemodus
    icon: mdi:home-circle-outline
